# ./docker-compose.yml

version: '3'

services:
  database:
    container_name: database
    image: mariadb:latest
    restart: always
    env_file: db.env
    volumes:
      - ./froxlor:/var/www/html/froxlor
    ports:
      - "9906:3306"

  froxlor:
    build: .
    container_name: froxlor
    depends_on:
      - database
    links:
      - "database:database"
    volumes:
      - ./froxlor:/var/www/html/froxlor
    restart: always
    ports:
      - 8080:80
    stdin_open: true
    tty: true
